[trading]
max_position_size = 1000.0
slippage_tolerance = 0.01
gas_price_gwei = 50
min_profit_threshold = 0.05

[hardware]
enable_gpu = true
cpu_threads = 8

[network]
rpc_url = "https://api.mainnet-beta.solana.com"
ws_url = "wss://api.mainnet-beta.solana.com"
helius_api_key = "your_api_key_here"
dev_mode = false

[sandwich]
max_front_run_amount = 100.0